config/routes.rb
ShowerPower::Application.routes.draw do
  match '/application.manifest', to: 'appcache#index', format: :appcache, as: :manifest
  match '/about', to: 'pages#about'
  root to: 'pages#index'
end

app/controllers/appcache_controller.rb
class AppcacheController < ApplicationController
  layout false

  def index
    render status: 404 if Rails.env.development?
  end

  protected
  def self.freshness
    if @freshness.blank? || !Rails.env.production?
      @freshness = {}
      filename = Rails.root.join('app', 'views', 'appcache', "index.appcache.erb")
      @freshness[page] = {
        last_modified: File.mtime(filename),
        etag: Digest::MD5.hexdigest(File.read(filename))
      }
    end
    @freshness
  end

  def set_http_caching(action)
    freshness = self.class.freshness[action]
    fresh_when last_modified: freshness[:last_modified], etag: freshness[:etag], public: true
    expires_in 10.minutes, public: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    set_http_caching(:index)
  end

  def about
    set_http_caching(:about)
  end

  protected
  def self.freshness
    if @freshness.blank? || !Rails.env.production?
      @freshness = {}
      [:index, :about].each do |page|
        filename = Rails.root.join('app', 'views', 'pages', "#{page}.html.erb")
        @freshness[page] = {
          last_modified: File.mtime(filename),
          etag: Digest::MD5.hexdigest(File.read(filename))
        }
      end
    end
    @freshness
  end

  def set_http_caching(action)
    freshness = self.class.freshness[action]
    fresh_when last_modified: freshness[:last_modified], etag: freshness[:etag], public: true
    expires_in 10.minutes, public: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appcache/index.appcache.erb
CACHE MANIFEST

<% if asset_paths.asset_digests.present? -%>
CACHE:
<% asset_paths.asset_digests.keys.each do |asset| -%>
<%= asset_path(asset) %>
<% end -%>
<% end -%>

NETWORK:
*

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= content_tag :html, manifest: Rails.env.development? ? nil : manifest_path do %>
  <head>
    <title>Shower Power</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-25704631-5']);
      _gaq.push(['_trackPageview']);

      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();

     </script>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Shower Power', root_path, class: 'brand' %>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="<%= request.path == root_path ? "active" : "" %>">
                <%= link_to 'Home', root_path %>
              </li>
              <li class="<%= request.path == about_path ? "active" : "" %>">
                <%= link_to 'About', about_path %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>

      <div id="footer">
        <hr>
        <p>
          Yet another daft wee app from
          <a href="http://woss.name" title="Notes from a Messy Desk">Graeme Mathieson</a>.
        </p>
      </div>
    </div>
  </body>
<% end %>

app/views/pages/about.html.erb
<div class="page-header">
  <h1>About</h1>
</div>

<p>
  I really did want to figure out how much the shower was costing me, and I
  really do want to encourage my son, Malcolm (aged 4) to spend less time in
  the shower. It's not like Malcolm will take any notice of hard data, but my
  wife, Annabel, might. :)
</p>

<p>
  However, there was another motive. I stumbled across a Javascript library
  called <a href="http://worrydream.com/Tangle/" title="Tangle: explorable
    explanations made easy">Tangle</a> which allows you to creative interactive
  documents. I'm quite irrationally excited about it because I'm envisaging a
  whole pile of situations where it would be awesomely useful. So I wanted to
  play around, see if I could make it work.
</p>

<p>
  Turns out it's pretty easy to work, and I reckon it works pretty well. What
  do you think?
</p>

<h2>Methodology</h2>

<p>
  Either I wasn't paying attention in Standard Grade Physics or it was just so
  long ago that I've forgotten it all. So I had to go look up how much it costs
  to heat water. Roughly speaking, here's what's happening:
</p>

<ol>
  <li>
    <p>
      Figure out how much we need to increase the water temperature by
      (<em>heated water temperature - incoming supply water temperature</em>).
    </p>
  </li>

  <li>
    <p>
      Figure out the total number of litres of water by multiplying the flow rate
      (per minute) by the number of minutes spent in the shower.
    </p>
  </li>

  <li>
    <p>
      Figure out the number of litres of hot water being used, by figuring out
      the mix of hot:cold being done at the shower.
    </p>
  </li>

  <li>
    <p>
      It turns out the weight (erm, mass, maybe? see above about paying attention
      in physics!) isn't quite the same as the number of litres. I pretended to
      care about this by multiplying is by 0.99225, the relative mass at
      40&deg;C.
    </p>
  </li>

  <li>
    <p>
      The specific heat capacity of water (the amount of energy require to
      increase the water's temperature by 1&deg;C) is 1 calorie per
      cm<sup>3</sup>, which is equivalent to 4,186 joules/kg. So multiply the
      mass of the hot water by the increase in temperature and multiple that by
      this specific heat capacity and you've got the number of joules of energy
      required to heat the water up.
    </p>
  </li>

  <li>
    <p>
      Divide that by the efficiency of the boiler, and you'll get the number of
      joules your crappy boiler needs to spend to heat up the water.
    </p>
  </li>

  <li>
    <p>
      Now divide the number of joules by 3.6 million to convert it to kWh.
    </p>
  </li>

  <li>
    <p>
      And finally multiply it by the cost per kWh. One cost, at last!
    </p>
  </li>
</ol>

<p>
  Have I got the methodology about right? I hope so!
</p>

<p>
  Have something to say? Drop me a wee email to <%= mail_to 'mathie@woss.name' %>
and let me know what you think!
  </p>

app/views/pages/index.html.erb
<div class="page-header">
  <h1>Shower Power!</h1>
</div>

<div class="row">
  <div class="span8" id="showerCosts">
    <p>
      My son takes <em>ages</em> in the shower.
      Like <span data-var="minutesInShower" class="TKAdjustableNumber" data-min="0" data-max="60"> minutes</span>.
      I swear it's costing a fortune, but my wife doesn't believe me. These are
      the sorts of lengths I'll go to, just to prove I'm right.
    </p>

    <p>
      It turns out, given the other variables below, it costs
      <strong>
        &pound;<span data-var="totalCost" data-format="%.02f"></span>
      </strong>
      every time my son has a shower. He generally showers
      <span data-var="showerFrequency" class="TKAdjustableNumber" data-min="0" data-max="3" data-format="showerFrequency"> </span>
      which means it's costing me
      <strong>
        &pound;<span data-var="annualCost" data-format="%.02f"></span>
      </strong>
      every year to keep him clean!
    </p>

    <p>
      How do you compare? Grab the highlighted numbers and drag them around to
      see how much money you're pouring down the drain!
    </p>

    <h2>Water coming in</h2>

    <p>
      The water comes into our house at about
      <span data-var="incomingWaterTemperature" class="TKAdjustableNumber" data-min="-10" data-max="20">&deg;C</span>
      on average throughout the year. Our boiler then heats it up to about
      <span data-var="heatedWaterTemperature" class="TKAdjustableNumber" data-min="10" data-max="100">&deg;C</span>
      before it gets mixed with cold water at the shower. (It turns out that the
      temperature the boiler heats it to doesn't really matter &ndash; try
      playing with the numbers if you don't believe me!)
    </p>

    <p>
      This means the boiler (which is
      <span data-var="boilerEfficiency" class="TKAdjustableNumber" data-min="0" data-max="1" data-step="0.01" data-format="percent"></span>
      efficient at heating water) needs to heat the water by about
      <span data-var="waterTemperatureDelta">&deg;C</span>.
    </p>

    <h2>Shower</h2>

    <p>
      Our shower pushes out
      <span data-var="showerFlowRate" class="TKAdjustableNumber" data-min="0" data-max="30"> litres</span>
      of water every minute. That means I'm pouring
      <span data-var="litresOfWater"> litres</span> of water down the drain when he has a shower.
    </p>

    <p>
      The target water temperature for a pleasant shower is
      <span data-var="targetShowerTemperature" class="TKAdjustableNumber" data-min="0" data-max="50">&deg;C</span>.
      In order to get that, we need to mix
      <span data-var="percentageHotWater" data-format="percent"></span> hot water with
      <span data-var="percentageColdWater" data-format="percent"></span> cold. Which means we're heating
      <span data-var="litresOfHotWater" data-format="%d"> litres</span> of hot water for the shower.
    </p>

    <h2>Costs</h2>

    <p>
      It costs us
      <span data-var="gasCost" class="TKAdjustableNumber" data-min="0.00" data-max="0.20" data-step="0.001" data-format="pence"></span>
      per kWh for our gas and
      <span data-var="waterCost" class="TKAdjustableNumber" data-min="0.00" data-max="0.20" data-step="0.0001" data-format="pence"></span>
      per litre for our water (including sewerage).
    </p>
  </div>

  <div class="span4">
    <div class="well">
      <h2>Making Changes</h2>

      <p>You can change any of the numbers that are highlighted in blue with
        dotted underlines. Just click and drag the values left and right to
        change. You're most likely to want to change:</p>

      <ul>
        <li><p>The amount of time spent in the shower. Nobody spends <em>that</em>
            much time in the shower, right?</p></li>

        <li><p>The volume of water the shower emits. We've got one of those rain
            shower heads, so we're a bit above average. I believe the normal rate
            is around 9l/minute.</p></li>

        <li><p>The costs. We live in Scotland and don't pay for water. Water can be
            expensive!</p></li>
      </ul>
    </div>
  </div>
</div>